###### import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices2.csv")
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df.bedrooms.median()

4.0

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [7]:
median_bedrooms

4

In [21]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [22]:
df

area  bedrooms  age   price
0  2600         4   20  550000
1  3000         4   15  565000
2  3200         4   18  610000
3  3600         4   30  595000
4  4000         4    8  760000
5  4100         4    8  810000

In [23]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [24]:
reg.coef_
reg.intercept_

284042.1639073314

In [26]:
reg.predict([[3000, 3, 40]])
reg.predict([[3000, 3, 15]])
reg.predict([[2500, 4, 5]])

array([589243.93156288])

In [13]:
reg.predict([[3000, 3, 40]])


array([498408.25158031])

In [14]:
reg.predict([[3000, 3, 15]])


array([579201.19929613])

In [27]:
reg.predict([[3000, 4, 15]])

array([601108.98674959])