In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [1]:
df = pd.read_csv("homeprices.csv")

NameError: name 'pd' is not defined

In [3]:
df

town  area   price
0    shymkent  2600  550000
1    shymkent  3000  565000
2    shymkent  3200  610000
3    shymkent  3600  680000
4    shymkent  4000  725000
5      almaty  2600  585000
6      almaty  2800  615000
7      almaty  3300  650000
8      almaty  3600  710000
9   nursultan  2600  575000
10  nursultan  2900  600000
11  nursultan  3100  620000
12  nursultan  3600  695000

In [6]:
pd.get_dummies(df.town)
dummies = pd.get_dummies(df.town)

In [7]:
dummies

almaty  nursultan  shymkent
0        0          0         1
1        0          0         1
2        0          0         1
3        0          0         1
4        0          0         1
5        1          0         0
6        1          0         0
7        1          0         0
8        1          0         0
9        0          1         0
10       0          1         0
11       0          1         0
12       0          1         0

In [11]:
merged = pd.concat([df, dummies], axis = 'columns')

In [14]:
merged


town  area   price  almaty  nursultan  shymkent
0    shymkent  2600  550000       0          0         1
1    shymkent  3000  565000       0          0         1
2    shymkent  3200  610000       0          0         1
3    shymkent  3600  680000       0          0         1
4    shymkent  4000  725000       0          0         1
5      almaty  2600  585000       1          0         0
6      almaty  2800  615000       1          0         0
7      almaty  3300  650000       1          0         0
8      almaty  3600  710000       1          0         0
9   nursultan  2600  575000       0          1         0
10  nursultan  2900  600000       0          1         0
11  nursultan  3100  620000       0          1         0
12  nursultan  3600  695000       0          1         0

In [15]:
final = merged.drop(['town','nursultan'], axis = 'columns')

In [16]:
final

area   price  almaty  shymkent
0   2600  550000       0         1
1   3000  565000       0         1
2   3200  610000       0         1
3   3600  680000       0         1
4   4000  725000       0         1
5   2600  585000       1         0
6   2800  615000       1         0
7   3300  650000       1         0
8   3600  710000       1         0
9   2600  575000       0         0
10  2900  600000       0         0
11  3100  620000       0         0
12  3600  695000       0         0

In [20]:
model = LinearRegression()

In [21]:
X = final.drop(['price'], axis = 'columns')

In [22]:
X

area  almaty  shymkent
0   2600       0         1
1   3000       0         1
2   3200       0         1
3   3600       0         1
4   4000       0         1
5   2600       1         0
6   2800       1         0
7   3300       1         0
8   3600       1         0
9   2600       0         0
10  2900       0         0
11  3100       0         0
12  3600       0         0

In [23]:
y = final.price

In [24]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [25]:
model.fit(X,y)

LinearRegression()

In [26]:
model.predict([[2800, 0, 0]])

array([590775.6396474])

In [29]:
model.predict([[3400, 1, 0]])

array([681241.66845839])

In [30]:
model.score(X,y)

0.9573929037221873

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
le = LabelEncoder()

In [34]:
dfle = df
dfle.town = le.fit_transform(dfle.town)

In [35]:
df

town  area   price
0      2  2600  550000
1      2  3000  565000
2      2  3200  610000
3      2  3600  680000
4      2  4000  725000
5      0  2600  585000
6      0  2800  615000
7      0  3300  650000
8      0  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [54]:
X = df[['town', 'area']].values

In [55]:
X

array([[   2, 2600],
       [   2, 3000],
       [   2, 3200],
       [   2, 3600],
       [   2, 4000],
       [   0, 2600],
       [   0, 2800],
       [   0, 3300],
       [   0, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [45]:
y = dfle.price

In [46]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [3]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough' 
)
X = ct.fit_transform(X)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough' 
)
X = ct.fit_transform(X)


NameError: name 'X' is not defined

In [2]:
X = ct.fit_transform(X)

NameError: name 'ct' is not defined

In [58]:
X

array([[0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 4.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.8e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.3e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [59]:
X = X[:,1:]

In [60]:
X

array([[0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [61]:
model.fit(X,y)

LinearRegression()

In [65]:
model.predict([[1,0,2800]])

array([590775.63964738])

In [67]:
model.predict([[0,0,3400]])

array([681241.6684584])