In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("test_scores.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [3]:
reg = linear_model.LinearRegression()
reg.fit(df[['math']], df.cs)

LinearRegression()

In [4]:
reg.predict([[84]])

array([87.40506329])

In [6]:
reg.predict([[56]])

array([58.90844863])

In [8]:
reg.coef_

array([1.01773624])

In [9]:
reg.intercept_

1.9152193111569034